### ISSUE TITLE
the MOD stopped working

### ISSUE THREAD

**Issue by NOOBmorreparaMIM** [drdaxxy/gta5fov#15] opened 2016-12-15 21:46 UTC
Please drdaxxy Updates because is not working!!! thanks!!!I await!!!!

**Comment by rsgg** [comment] 2016-12-15 22:25
Refer to https://github.com/drdaxxy/gta5fov/issues/14 for a temporary fix until this is updated.

**Comment by drdaxxy** [comment] 2017-02-03 10:33
Duplicate of #14

**Closed as completed by drdaxxy** 2017-02-03 10:33 UTC
